# Changes here will be overwritten by Copier
_commit: 8c7effc
_src_path: ~/code/yapy-copier-template
author_count: 1
author_emails: dev@ingobressler.net
author_names: Ingo Breßler
author_websites: https://github.com/ibressler
copyright_from: 2018
copyright_to: 2023
docs_url: https://BAMresearch.github.io/jupyter-analysis-tools
license: MIT
project_description: Yet another Python library with helpers and utilities for data
    analysis and processing.
project_name: Jupyter Analysis Tools
pypi_host: pypi.org
release_date_question: today
repo_hosting_domain: github.com
repo_main_branch: main
repo_name: jupyter-analysis-tools
repo_userorg: BAMresearch
sphinx_theme: furo
version: 1.3.0
