github_url = "https://github.com/BAMresearch/jupyter_analysis_tools/"

[version]
current = "0.1.0"
regex = '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)'

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "setup.py"
search = "version='{current_version}'"

[[file]]
src = "README.rst"
search = "/v{current_version}.svg"

[[file]]
src = "README.rst"
search = "/v{current_version}...main"

[[file]]
src = "docs/conf.py"
search = "version = release = '{current_version}'"

[[file]]
src = "src/jupyter_analysis_tools/__init__.py"
search = "__version__ = '{current_version}'"

[[before_commit]]
name = "check changelog"
cmd = "grep -q {new_version} CHANGELOG.rst"

# Or run some commands after the git tag and the branch
# have been pushed:
#  [[after_push]]
#  name = "publish"
#  cmd = "./publish.sh"
