name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

jobs:
  # defining this job separately allows to refer to it later
  # as job.needs dependency plus it provides a badge
  build:
    # Only run this job if new work is pushed to "main"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # convert this to a matrix if builds differ between platforms
    runs-on: {{'${{ matrix.os }}'}}
    strategy:
      matrix:
        os: ['ubuntu-latest']
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '{{ py_ver }}' # defined by py_ver in ci/bootstrap.py
        cache: pip
        cache-dependency-path: ci/requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --progress-bar=off -r ci/requirements.txt
        python -m pip install build

    - name: Build
      run: python -m build

    - name: Upload package artifact for publishing job
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: dist/*.whl

    - name: Upload source artifact for publishing job
      # upload source package only once
      if: {{"${{ matrix.os == 'ubuntu-latest' }}"}}
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: dist/*.tar.gz

  publish:
    needs: [build]
    runs-on: 'ubuntu-latest'
    steps:

    # - uses: actions/setup-python@v4
    #   with:
    #     python-version: '{{ py_ver }}' # defined by py_ver in ci/bootstrap.py
    #     cache: pip
    #     cache-dependency-path: ci/requirements.txt

    - name: Download package artifacts
      uses: actions/download-artifact@v3
      with:
        name: packages

    - run: |
        ls -la
        ls -la packages

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: {{'${{ secrets.TEST_PYPI_API_TOKEN }}'}}
        repository_url: https://test.pypi.org/legacy/
