name: CI-CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    # defining jobs separately allows to refer to them later
    # as job.needs dependency plus it provides a badge
  docs:
    uses: ./.github/workflows/docs.yml

  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: [test]
    uses: ./.github/workflows/build.yml
    secrets: inherit
