name: Docs

# Controls when the action will run.
on:
  workflow_call:

jobs:
  docs:
    # defining this job separately allows to refer to it later as job.needs dependency
    runs-on: ubuntu-latest
    steps:

      - name: Checking out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # see *py_ver* in ci/update.py
      - name: Setting up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: |
            ci/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --progress-bar=off -r ci/requirements.txt

      - name: Check
        run: tox -e check -v

      - name: Generate documentation
        run: tox -e docs -v

      - name: Upload docs for finalization later
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: dist/docs

      # - name: Upload generated documentation
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./dist/docs
