name: Docs

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

jobs:
  docs:
    # defining this job separately allows to refer to it later
    # as job.needs dependency plus it provides a badge
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' # defined by py_ver in ci/bootstrap.py
        cache: pip
        cache-dependency-path: ci/requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --progress-bar=off -r ci/requirements.txt

    - name: Setup developmental version number
      if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        semantic-release --prerelease version

    - name: Check
      run: tox -e check -v

    - name: Generate documentation
      run: tox -e docs -v

    - name: Upload generated documentation
      if: ${{ matrix.tox_env == 'docs' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/docs
