name: Tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_docs:
    runs-on: ubuntu-latest
#    env:
#      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      # https://github.com/actions/cache/blob/main/examples.md#using-pip-to-get-cache-location
      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python3 -m pip install -r ./docs/requirements.txt

      - name: Build the Documentation with Sphinx
        run: |
          sphinx-build -b html docs build
          touch build/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'py38 (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38'
            os: 'ubuntu-latest'
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.python_arch }}
        cache: pip
        cache-dependency-path: |
          ci/requirements.txt
          tests/requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --progress-bar=off -r ci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
        pip list --format=freeze

    - name: Run tests
      env:
        TOXPYTHON: '${{ matrix.toxpython }}'
      run: tox -e ${{ matrix.tox_env }} -v

    - name: Rename coverage data uniquely
      if: ${{ startsWith(matrix.tox_env, 'py') }}
      run: mv .coverage coverage.${{ matrix.python }}.${{ matrix.os }}

    - name: Upload coverage data
      if: ${{ startsWith(matrix.tox_env, 'py') }}
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage.*

  combine:
    name: Combine coverage data
    needs: test
    runs-on: ubuntu-latest
    outputs:
      total: ${{ steps.total.outputs.total }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 # Minimum of PYVERSIONS
          cache: pip
          cache-dependency-path: |
            ci/requirements.txt
            tests/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --progress-bar=off -r ci/requirements.txt

      - name: Download coverage data
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: Combine and report
        id: combine
        run: |
          pwd && ls -la
          coverage combine coverage.*
          coverage html

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: html_report
          path: htmlcov

      - name: Get total
        id: total
        run: |
          echo "total=$(coverage report --format=total)" >> $GITHUB_OUTPUT

  publish:
    name: Publish coverage report
    needs: [combine, build_docs]
    runs-on: ubuntu-latest

    steps:
      - name: Compute info for later steps
        id: info
        run: |
          set -xe
          export SHA10=$(echo ${{ github.sha }} | cut -c 1-10)
          export SLUG=$(date +'%Y%m%d')_$SHA10
          export REPORT_BASE_DIR=coverage-report
          export REPORT_DIR=$REPORT_BASE_DIR/$SLUG
          export REF="${{ github.ref }}"
          echo "total=${{ needs.combine.outputs.total }}" >> $GITHUB_ENV
          echo "sha10=$SHA10" >> $GITHUB_ENV
          echo "slug=$SLUG" >> $GITHUB_ENV
          echo "report_base_dir=$REPORT_BASE_DIR" >> $GITHUB_ENV
          echo "report_dir=$REPORT_DIR" >> $GITHUB_ENV
          echo "url=https://bamresearch.github.io/jupyter_analysis_tools/$REPORT_DIR" >> $GITHUB_ENV
          echo "branch=${REF#refs/heads/}" >> $GITHUB_ENV

      - name: Summarize
        run: |
          echo '### Total coverage: ${{ env.total }}%' >> $GITHUB_STEP_SUMMARY

      - name: Checkout reports branch
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: pages

      - name: Download coverage HTML report
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/download-artifact@v3
        with:
          name: html_report
          path: pages/${{ env.report_dir }}

      - name: Push to report repo
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          set -xe
          # Make the redirect to the latest report.
          echo "<html><head>" > pages/${{ env.report_base_dir }}/latest.html
          echo "<meta http-equiv='refresh' content='0;url=${{ env.url }}' />" >> pages/${{ env.report_base_dir }}/latest.html
          echo "<body>Coverage report redirect..." >> pages/${{ env.report_base_dir }}/latest.html
          # Make the commit message.
          echo "${{ env.total }}% - $COMMIT_MESSAGE" > commit.txt
          echo "" >> commit.txt
          echo "${{ env.url }}" >> commit.txt
          echo "${{ env.sha10 }}: ${{ env.branch }}" >> commit.txt
          # Make badge json
          COL_MIN=10; COL_MAX=95;
          HUE=$(python3 -c "print(int((${{ env.total }} - $COL_MIN)/($COL_MAX - $COL_MIN) * 120))")
          echo "{\"schemaVersion\":1,\"label\":\"Coverage\",\"message\":\"${{ env.total }}%\",\"color\":\"hsl($HUE, 100%, 40%)\"}" >> pages/${{ env.report_base_dir }}/cov.json
          # Commit.
          cd ./pages
          rm ${{ env.report_dir }}/.gitignore
          ls -la ${{ env.report_dir }} # for debugging
          git sparse-checkout set --skip-checks '/*' '${{ env.report_dir }}'
          git add ${{ env.report_dir }}/* ${{ env.report_base_dir }}/latest.html ${{ env.report_base_dir }}/cov.json
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit --file=../commit.txt
          git push
          echo '[${{ env.url }}](${{ env.url }})' >> $GITHUB_STEP_SUMMARY
