name: Testing

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "testing"
  testing:
    name: Testing (${{ matrix.python-version }}, ${{ matrix.os }})
    # The type of runner that the job will run on (each of the os matrix below)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest",]
        # "macos-latest", "windows-latest"]
        python-version: ["3.9",]
        # "3.8"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          conda env list
          conda list
          echo "## conda env export --no-builds"
          conda env export --no-builds
          echo "## conda list -e"
          conda list -e
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setting up environment
        shell: bash -l {0}
        run: |
          echo "## conda env create -f conda_environment.yml"
          ls -la && pwd
          conda env create -f conda_environment.yml
          echo "## conda list -e"
          conda list -e
      - name: Testing things
        shell: bash -l {0}
        run: |
          ls -la
          python -m doctest -v utils.py
